export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum StageName {
  NAO_INICIADO = 'NAO_INICIADO',
  MODELAGEM_NEGOCIO = 'MODELAGEM_NEGOCIO',
  MODELAGEM_TI = 'MODELAGEM_TI',
  DESENVOLVIMENTO = 'DESENVOLVIMENTO',
  HOMOLOGACAO = 'HOMOLOGACAO',
  FINALIZADO = 'FINALIZADO',
}

export enum StageStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  BLOCKED = 'BLOCKED',
}
